parameters:
    access_tokens: '%env(ACCESS_TOKENS)%'
    store_link_api: '%env(STORE_LINK_API)%'
    store_link_api_token: '%env(STORE_LINK_API_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    event_subscribers:
        namespace: App\Event\Subscriber\
        resource: '../src/Event/Subscriber'
        arguments: [ '@parameter_bag', '@logger' ]
        tags: [event_subscriber]

    App\Services\EvilLinks\HasWordsPostTransformer:
        class: App\Services\EvilLinks\HasWordsPostTransformer
        arguments:
            $words: '%env(WORDS_FILTER_PHRASES)%'

    App\Services\EvilLinks\CanHaveLinksPostTransformer:
        class: App\Services\EvilLinks\CanHaveLinksPostTransformer
        arguments:
            $whitelist: '%env(TELEGRAM_FILTER_WHITELIST)%'

    App\Services\EvilLinks\EvilLinksGrabber:
        class: App\Services\EvilLinks\EvilLinksGrabber
        arguments:
            $sources: '%env(GRABBER_SOURCES)%'
            $transformers:
                - '@App\Services\EvilLinks\HasWordsPostTransformer'
                - '@App\Services\EvilLinks\AuthorPostTransformer'
                - '@App\Services\EvilLinks\TelegramLinksPostTransformer'
                - '@App\Services\EvilLinks\YoutubeLinksPostTransformer'
                - '@App\Services\EvilLinks\TwitterLinksPostTransformer'
                - '@App\Services\EvilLinks\CanHaveLinksPostTransformer'
                - '@App\Services\EvilLinks\NoEmptyLinksPostTransformer'
                - '@App\Services\EvilLinks\TimePostTransformer'
                - '@App\Services\EvilLinks\ViewsPostTransformer'

    App\Services\EvilLinks\EvilLinksGrabberInterface $evilLinksGrabber: '@App\Services\EvilLinks\EvilLinksGrabber'
    App\Services\EvilLinks\EvilLinksGrabberInterface: '@App\Services\EvilLinks\EvilLinksGrabber'